/* deno-fmt-ignore-file */
import { delay } from "./delay.ts";

type AsyncFunction<T, U> = (input: Awaited<T>) => U | Promise<U>;

export function asyncFlow<A, B>(f1: AsyncFunction<A, B>): (input: A | Promise<A>) => Promise<Awaited<B>>;
export function asyncFlow<A, B, C>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>): (input: A | Promise<A>) => Promise<Awaited<C>>;
export function asyncFlow<A, B, C, D>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>): (input: A | Promise<A>) => Promise<Awaited<D>>;
export function asyncFlow<A, B, C, D, E>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>): (input: A | Promise<A>) => Promise<Awaited<E>>;
export function asyncFlow<A, B, C, D, E, F>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>): (input: A | Promise<A>) => Promise<Awaited<F>>;
export function asyncFlow<A, B, C, D, E, F, G>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>): (input: A | Promise<A>) => Promise<Awaited<G>>;
export function asyncFlow<A, B, C, D, E, F, G, H>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>): (input: A | Promise<A>) => Promise<Awaited<H>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>): (input: A | Promise<A>) => Promise<Awaited<I>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>): (input: A | Promise<A>) => Promise<Awaited<J>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>): (input: A | Promise<A>) => Promise<Awaited<K>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>): (input: A | Promise<A>) => Promise<Awaited<L>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>): (input: A | Promise<A>) => Promise<Awaited<M>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>): (input: A | Promise<A>) => Promise<Awaited<N>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>): (input: A | Promise<A>) => Promise<Awaited<O>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>): (input: A | Promise<A>) => Promise<Awaited<P>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>): (input: A | Promise<A>) => Promise<Awaited<Q>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>): (input: A | Promise<A>) => Promise<Awaited<R>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>): (input: A | Promise<A>) => Promise<Awaited<S>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>): (input: A | Promise<A>) => Promise<Awaited<T>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>, f20: AsyncFunction<T, U>): (input: A | Promise<A>) => Promise<Awaited<U>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>, f20: AsyncFunction<T, U>, f21: AsyncFunction<U, V>): (input: A | Promise<A>) => Promise<Awaited<V>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>, f20: AsyncFunction<T, U>, f21: AsyncFunction<U, V>, f22: AsyncFunction<V, W>): (input: A | Promise<A>) => Promise<Awaited<W>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>, f20: AsyncFunction<T, U>, f21: AsyncFunction<U, V>, f22: AsyncFunction<V, W>, f23: AsyncFunction<W, X>): (input: A | Promise<A>) => Promise<Awaited<X>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>, f20: AsyncFunction<T, U>, f21: AsyncFunction<U, V>, f22: AsyncFunction<V, W>, f23: AsyncFunction<W, X>, f24: AsyncFunction<X, Y>): (input: A | Promise<A>) => Promise<Awaited<Y>>;
export function asyncFlow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z>(f1: AsyncFunction<A, B>, f2: AsyncFunction<B, C>, f3: AsyncFunction<C, D>, f4: AsyncFunction<D, E>, f5: AsyncFunction<E, F>, f6: AsyncFunction<F, G>, f7: AsyncFunction<G, H>, f8: AsyncFunction<H, I>, f9: AsyncFunction<I, J>, f10: AsyncFunction<J, K>, f11: AsyncFunction<K, L>, f12: AsyncFunction<L, M>, f13: AsyncFunction<M, N>, f14: AsyncFunction<N, O>, f15: AsyncFunction<O, P>, f16: AsyncFunction<P, Q>, f17: AsyncFunction<Q, R>, f18: AsyncFunction<R, S>, f19: AsyncFunction<S, T>, f20: AsyncFunction<T, U>, f21: AsyncFunction<U, V>, f22: AsyncFunction<V, W>, f23: AsyncFunction<W, X>, f24: AsyncFunction<X, Y>, f25: AsyncFunction<Y, Z>): (input: A | Promise<A>) => Promise<Awaited<Z>>;

export function asyncFlow<T, Fns extends AsyncFunction<any, any>[]>(...fns: Fns): (input: T | Promise<T>) => Promise<Awaited<ReturnType<Fns[number]>>> {
  return (input: T | Promise<T>) => fns.reduce<Promise<any>>((acc, fn) => acc.then(fn), Promise.resolve(input));
}

if (import.meta.main) {
  const flow = asyncFlow(
    (x: number) => x * 2,
    async (x) => {
      await delay(1000);
      return x + 2;
    },
    (x) => x.toString()
  );

  console.log(await flow(2));
}
