/* deno-fmt-ignore-file */
import { delay } from "./delay.ts";

type AsyncFunction<T, U> = (input: Awaited<T>) => U | Promise<U>;

export function asyncPipe<A>(f1: A | Promise<A>): Promise<Awaited<A>>;
export function asyncPipe<A, B>(f1: A | Promise<A>, f2: AsyncFunction<A, B>,): Promise<Awaited<B>>;
export function asyncPipe<A, B, C>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>,): Promise<Awaited<C>>;
export function asyncPipe<A, B, C, D>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>,): Promise<Awaited<D>>;
export function asyncPipe<A, B, C, D, E>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>,): Promise<Awaited<E>>;
export function asyncPipe<A, B, C, D, E, F>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>,): Promise<Awaited<F>>;
export function asyncPipe<A, B, C, D, E, F, G>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>,): Promise<Awaited<G>>;
export function asyncPipe<A, B, C, D, E, F, G, H>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>,): Promise<Awaited<H>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>,): Promise<Awaited<I>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>,): Promise<Awaited<J>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>,): Promise<Awaited<K>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>,): Promise<Awaited<L>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>,): Promise<Awaited<M>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>,): Promise<Awaited<N>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>,): Promise<Awaited<O>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>,): Promise<Awaited<P>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>,): Promise<Awaited<Q>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>,): Promise<Awaited<R>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>,): Promise<Awaited<S>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>,): Promise<Awaited<T>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>, f21: AsyncFunction<T, U>,): Promise<Awaited<U>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>, f21: AsyncFunction<T, U>, f22: AsyncFunction<U, V>,): Promise<Awaited<V>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>, f21: AsyncFunction<T, U>, f22: AsyncFunction<U, V>, f23: AsyncFunction<V, W>,): Promise<Awaited<W>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>, f21: AsyncFunction<T, U>, f22: AsyncFunction<U, V>, f23: AsyncFunction<V, W>, f24: AsyncFunction<W, X>,): Promise<Awaited<X>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>, f21: AsyncFunction<T, U>, f22: AsyncFunction<U, V>, f23: AsyncFunction<V, W>, f24: AsyncFunction<W, X>, f25: AsyncFunction<X, Y>,): Promise<Awaited<Y>>;
export function asyncPipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z>(f1: A | Promise<A>, f2: AsyncFunction<A, B>, f3: AsyncFunction<B, C>, f4: AsyncFunction<C, D>, f5: AsyncFunction<D, E>, f6: AsyncFunction<E, F>, f7: AsyncFunction<F, G>, f8: AsyncFunction<G, H>, f9: AsyncFunction<H, I>, f10: AsyncFunction<I, J>, f11: AsyncFunction<J, K>, f12: AsyncFunction<K, L>, f13: AsyncFunction<L, M>, f14: AsyncFunction<M, N>, f15: AsyncFunction<N, O>, f16: AsyncFunction<O, P>, f17: AsyncFunction<P, Q>, f18: AsyncFunction<Q, R>, f19: AsyncFunction<R, S>, f20: AsyncFunction<S, T>, f21: AsyncFunction<T, U>, f22: AsyncFunction<U, V>, f23: AsyncFunction<V, W>, f24: AsyncFunction<W, X>, f25: AsyncFunction<X, Y>, f26: AsyncFunction<Y, Z>,): Promise<Awaited<Z>>;

export function asyncPipe<T, Fns extends (AsyncFunction<any, any>)[]>(initialValue: T | Promise<T>, ...restFns: Fns): Promise<Awaited<ReturnType<Fns[number]>>> {
  return restFns.reduce<Promise<any>>((acc, fn) => acc.then(fn), Promise.resolve(initialValue));
}

if (import.meta.main) {
  console.log(
    await asyncPipe(
      2,
      (x) => x * 2,
      async (x) => {
        await delay(1000);
        return x + 2;
      },
    )
  )
}
