/* deno-fmt-ignore-file */
export function flow<A, B>(fn1: (value: A) => B): B;
export function flow<A, B, C>(fn1: (value: A) => B, fn2: (value: B) => C): C;
export function flow<A, B, C, D>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D): D;
export function flow<A, B, C, D, E>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E): E;
export function flow<A, B, C, D, E, F>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F): F;
export function flow<A, B, C, D, E, F, G>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G): G;
export function flow<A, B, C, D, E, F, G, H>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H): H;
export function flow<A, B, C, D, E, F, G, H, I>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I): I;
export function flow<A, B, C, D, E, F, G, H, I, J>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J): J;
export function flow<A, B, C, D, E, F, G, H, I, J, K>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K): K;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L): L;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M): M;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N): N;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O): O;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P): P;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q): Q;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R): R;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S): S;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T): T;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U): U;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V): V;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W): W;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W, fn23: (value: W) => X): X;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W, fn23: (value: W) => X, fn24: (value: X) => Y): Y;
export function flow<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z>(fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W, fn23: (value: W) => X, fn24: (value: X) => Y, fn25: (value: Y) => Z): Z;

export function flow(...fns: ((value: unknown) => unknown)[]) {
  return (value: unknown) => fns.reduce((acc, fn) => fn(acc), value);
}
