/* deno-fmt-ignore-file */
export function pipe<A>(value: A): A;
export function pipe<A, B>(value: A, fn1: (value: A) => B): B;
export function pipe<A, B, C>(value: A, fn1: (value: A) => B, fn2: (value: B) => C): C;
export function pipe<A, B, C, D>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D): D;
export function pipe<A, B, C, D, E>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E): E;
export function pipe<A, B, C, D, E, F>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F): F;
export function pipe<A, B, C, D, E, F, G>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G): G;
export function pipe<A, B, C, D, E, F, G, H>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H): H;
export function pipe<A, B, C, D, E, F, G, H, I>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I): I;
export function pipe<A, B, C, D, E, F, G, H, I, J>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J): J;
export function pipe<A, B, C, D, E, F, G, H, I, J, K>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K): K;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L): L;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M): M;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N): N;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O): O;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P): P;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q): Q;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R): R;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S): S;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T): T;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U): U;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V): V;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W): W;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W, fn23: (value: W) => X): X;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W, fn23: (value: W) => X, fn24: (value: X) => Y): Y;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z>(value: A, fn1: (value: A) => B, fn2: (value: B) => C, fn3: (value: C) => D, fn4: (value: D) => E, fn5: (value: E) => F, fn6: (value: F) => G, fn7: (value: G) => H, fn8: (value: H) => I, fn9: (value: I) => J, fn10: (value: J) => K, fn11: (value: K) => L, fn12: (value: L) => M, fn13: (value: M) => N, fn14: (value: N) => O, fn15: (value: O) => P, fn16: (value: P) => Q, fn17: (value: Q) => R, fn18: (value: R) => S, fn19: (value: S) => T, fn20: (value: T) => U, fn21: (value: U) => V, fn22: (value: V) => W, fn23: (value: W) => X, fn24: (value: X) => Y, fn25: (value: Y) => Z): Z;

export function pipe(value: unknown, ...fns: ((value: unknown) => unknown)[]): unknown {
  return fns.reduce((v, fn) => fn(v), value);
}
